Auto charge / auto income
boardgamers/gaia-engine pull request #229
Opened 2021-02-15 21:36 UTC by zeitlinger

2021-02-16 18:15 UTC, coyotte508 requested changes

2021-02-16 18:15 UTC, coyotte508 commented on wrapper.ts
> +    itarsAutoChargeToArea3?: string;
Those can be boolean (checkbox). It's just there's no support for numbers, but there's support for booleans or string enums.

2021-02-16 18:15 UTC, coyotte508 commented on wrapper.ts
> +    itarsAutoChargeToArea3: String(engine.players[player].settings?.itarsAutoChargeToArea3),
Here just use  `!!`

```
autoIncome: !!engine.players[player].settings?.autoIncome,
```

2021-02-16 19:12 UTC, zeitlinger commented on package.json
> +    "nyc": "^15.1.0",
for running code coverage tests - it's not really important - I can remove it.

2021-02-16 20:27 UTC, coyotte508 commented on package.json
> +    "nyc": "^15.1.0",
It's fine (and maybe good!), just add the corresponding command to the package.json

2021-02-16 22:28 UTC, zeitlinger commented on src/available-command.ts
> +    return [earlyLeech];
that turned out to be a good idea, as it found a lot of corner cases :smile:

2021-02-16 22:28 UTC, zeitlinger commented on package.json
> +    "nyc": "^15.1.0",
some other time, when I need it again..

2021-02-16 22:51 UTC, coyotte508 commented
Thank you for the changes! This is going to be really cool, I'm also going to tweak BGS to show the Itars & Taklon settings only when the player has the corresponding Faction.

I will go over the code once again tomorrow evening and do some tests locally, maybe that will bleed a bit into Thursday.

2021-02-17 02:00 UTC, coyotte508 requested changes
The main point is making sure the player settings don't affect the move log. To test that, we can run some of the tests with some player settings enabled (and still without) to check that they work with the same move log. There is an example of when it fails in the comment in `income.ts`.

Do not hesitate to break up the PR if you want to continue working on some of the settings while others are ready. Or keep the one PR :)

2021-02-17 02:26 UTC, coyotte508 commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
To add to the comment, currently the `engine.autoCharge` function is only called in the wrapper - line `139`. The other automatic code based on settings - `autoIncome` and `autoBrainstone` - should only be called there. Either by editing the wrapper to call `engine.autoBrainstone()` and `engine.autoIncome()` as well, or by modifying/renaming `engine.autoCharge` to `engine.autoMove()` which does the bot move for the player: the auto charging, but also moving the brainstone / choosing the income.

2021-02-17 06:56 UTC, zeitlinger commented on src/income.ts
> +    runIncomeSimulation(data.clone(), beforeCharge, chargePowers, gainTokens)
Yes, this is done in https://github.com/boardgamers/gaia-engine/pull/229/files#diff-d43791db49a9902f2ab7530713f00aaf85be90ef60c61cf3b1e570ebf00bd38cR60

2021-02-17 07:17 UTC, zeitlinger commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
> I may be mistaken, but the feature you added recently

are you referring to taklons special leech?

2021-02-17 07:51 UTC, coyotte508 commented on src/income.ts
> +    runIncomeSimulation(data.clone(), beforeCharge, chargePowers, gainTokens)
Alright! It threw me off a bit. Maybe add a doc comment to `runIncomeSimulation` or just rename the last argument of `runIncomeSimulation` to `allGainTokens`

2021-02-17 07:57 UTC, coyotte508 commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
Oh never mind - I was mistaken. I thought the current code handled the income for the player if the order `[...gainTokens, ...chargePowers]` fully charged the income. It should be doable with `canFullyChargeDuringIncomePhase()` (in the current code). 

Anyway nevermind the 'Loss of functionality' part.

2021-02-17 08:31 UTC, zeitlinger commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
Addressed the replayability.

Can you add the test to Taklons? - I find the tests that replay entire games hard to follow.

2021-02-17 08:32 UTC, zeitlinger commented
> Do not hesitate to break up the PR if you want to continue working on some of the settings while others are ready. Or keep the one PR :)

no, there's no hurry.

2021-02-17 09:48 UTC, zeitlinger commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
regarding auto move separation:

I finished that part - I hope I got it right.

2021-02-17 09:50 UTC, zeitlinger commented on src/income.ts
> +}
I even tried to use https://github.com/SeregPie/lodash.combinations but that didn't have typescript definitions - and it wasn't very readable.

2021-02-17 11:39 UTC, zeitlinger commented
I guess we need to refactor the brainstone handling 

1. asking for brainstone destination should not be a separate step - it should rather be included in the charge options right away
2. this will also avoid the exception in the auto charge - where it asks for brainstone - which breaks the auto brainstone - IIUC

2021-02-17 18:49 UTC, coyotte508 commented on src/income.ts
> +    const auto = gainTokens.length === 0 || chargePowers.length === 0 || settings.autoIncome;
Thank you!

I'll merge and add the tests & stuff

2021-02-17 18:52 UTC, coyotte508 commented
Regarding the brainsone in a separate step - it should be possible to do it with the current setup, it's just that `autoBrainstone` and `autoCharge` would need to share some logic (specifically `autoCharge` would need to be aware of the player's `autoBrainstone` setting).

I'm not against refactoring if the current setup proves really impractical, but I think it can be done well enough as is - without making too many breaking changes to the format

2021-02-17 18:52 UTC, merged

2021-02-17 19:56 UTC, zeitlinger commented
> Regarding the brainsone in a separate step - it should be possible to do it with the current setup, it's just that `autoBrainstone` and `autoCharge` would need to share some logic (specifically `autoCharge` would need to be aware of the player's `autoBrainstone` setting).
> 
> I'm not against refactoring if the current setup proves really impractical, but I think it can be done well enough as is - without making too many breaking changes to the format of the logs

it was a bad idea - I tried it, but the code because rather messy.
I also convinced myself that the current setup should work :smile:

2021-02-17 22:27 UTC, coyotte508 commented
It sounds like a challenge!

I just tested locally and was confused when my taklons with autocharge 2pw and auto brainstone didn't leech. I guess no sleep for me today ^^

2021-02-18 04:29 UTC, zeitlinger commented
Did you get it to work?

On Wed, Feb 17, 2021, 23:27 coyotte508 <notifications@github.com> wrote:

> It sounds like a challenge!
>
> I just tested locally and was confused when my taklons with autocharge 2pw
> and auto brainstone didn't leech. I guess no sleep for me today ^^
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/boardgamers/gaia-engine/pull/229#issuecomment-780896142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAVTR45TIHMUYU3CC7Z64MDS7Q7GFANCNFSM4XVLBMYA>
> .
>

2021-02-18 08:32 UTC, coyotte508 commented
I think so!

I added some tests in the wrapper. I'll do some more testing before putting it live.